version: "3.8"

services:
  jobdb:
    image: mariadb:latest
    container_name: mariadb_job
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: admin1
      MARIADB_PASSWORD: root3
      MARIADB_DATABASE: job
    ports:
      - '3311:3306'
    volumes:
      - db_job_data:/var/lib/mysql

  userdb:
    image: mariadb:latest
    container_name: mariadb_user
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: adminers
      MARIADB_PASSWORD: root2
      MARIADB_DATABASE: auth
    ports:
      - '3309:3306'
    volumes:
      - db_user_data:/var/lib/mysql

  formationdb:
    image: mariadb:latest
    container_name: mariadb_formation
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: adminer
      MARIADB_PASSWORD: root1
      MARIADB_DATABASE: course
    ports:
      - '3307:3306'
    volumes:
      - db_formation_data:/var/lib/mysql

  phpmyadmin_formation:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_formation
    restart: always
    environment:
      PMA_HOST: formationdb
      PMA_USER: adminer
      PMA_PASSWORD: root1
    ports:
      - '8081:80'

  phpmyadmin_job:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_job
    restart: always
    environment:
      PMA_HOST: jobdb
      PMA_USER: admin1
      PMA_PASSWORD: root3
    ports:
      - '8082:80'

  phpmyadmin_user:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_user
    restart: always
    environment:
      PMA_HOST: userdb
      PMA_USER: adminers
      PMA_PASSWORD: root2
    ports:
      - '8083:80'

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    command: azurite-blob --blobHost 0.0.0.0 --location /data
    ports:
      - '10000:10000'
    volumes:
      - azurite_data:/data

volumes:
  db_job_data:
  db_user_data:
  db_formation_data:
  keycloak_data:
  azurite_data:
