version: "3.8"

services:
  jobdb:
    image: mariadb:latest
    container_name: mariadb_job
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: admin1
      MARIADB_PASSWORD: root3
      MARIADB_DATABASE: job
    ports:
      - '3311:3306'
    volumes:
      - db_job_data:/var/lib/mysql
  userdb:
    image: mariadb:latest
    container_name: mariadb_user
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: adminers
      MARIADB_PASSWORD: root2
      MARIADB_DATABASE: auth
    ports:
      - '3309:3306'
    volumes:
      - db_user_data:/var/lib/mysql
  formationdb:
    image: mariadb:latest
    container_name: mariadb_formation
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: adminer
      MARIADB_PASSWORD: root1
      MARIADB_DATABASE: course
    ports:
      - '3307:3306'
    volumes:
      - db_formation_data:/var/lib/mysql
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    command:
      - start-dev
      - --features=declarative-ui
    volumes:
      - keycloak_data:/opt/keycloak/data

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    command: azurite-blob --blobHost 0.0.0.0
    ports:
      - '10000:10000'
    volumes:
      - azurite_data:/data
volumes:
  db_job_data:
  db_user_data:
  db_formation_data:
  keycloak_data:
  azurite_data:


